#pragma once
#include "Obj_Buildings_Shinave.h"
#include "Obj_Mini_Platform_Set.h"
#include "Obj_Mini_Platform_Spawn.h"
#include "Obj_Mini_Stone_1.h"
#include "Obj_Puzzle_Mini_Stone_2.h"
#include "Obj_Puzzle_Mini_Stone_3.h"
#include "Obj_Puzzle_Mini_Stone_4.h"
#include "Obj_Puzzle_Mini_Stone_5.h"
