// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Connect.proto
// Protobuf C++ Version: 5.29.2

#include "Connect.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ConnectMsg {

inline constexpr SyncPlayer::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        position_{},
        resource_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR SyncPlayer::SyncPlayer(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SyncPlayerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SyncPlayerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SyncPlayerDefaultTypeInternal() {}
  union {
    SyncPlayer _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SyncPlayerDefaultTypeInternal _SyncPlayer_default_instance_;

inline constexpr SyncObject::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        position_{},
        rotation_{},
        scale_{},
        public__{false} {}

template <typename>
PROTOBUF_CONSTEXPR SyncObject::SyncObject(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SyncObjectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SyncObjectDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SyncObjectDefaultTypeInternal() {}
  union {
    SyncObject _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SyncObjectDefaultTypeInternal _SyncObject_default_instance_;

inline constexpr EnterAccept::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        grantnumber_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EnterAccept::EnterAccept(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EnterAcceptDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EnterAcceptDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EnterAcceptDefaultTypeInternal() {}
  union {
    EnterAccept _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EnterAcceptDefaultTypeInternal _EnterAccept_default_instance_;

inline constexpr AddRemote::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        grantnumber_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AddRemote::AddRemote(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AddRemoteDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddRemoteDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddRemoteDefaultTypeInternal() {}
  union {
    AddRemote _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddRemoteDefaultTypeInternal _AddRemote_default_instance_;

inline constexpr AddObject::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        resourceid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        grantnumber_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AddObject::AddObject(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AddObjectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddObjectDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddObjectDefaultTypeInternal() {}
  union {
    AddObject _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddObjectDefaultTypeInternal _AddObject_default_instance_;
}  // namespace ConnectMsg
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Connect_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Connect_2eproto = nullptr;
const ::uint32_t
    TableStruct_Connect_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::EnterAccept, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::EnterAccept, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::EnterAccept, _impl_.grantnumber_),
        0,
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::SyncPlayer, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::SyncPlayer, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::SyncPlayer, _impl_.position_),
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::SyncPlayer, _impl_.resource_),
        ~0u,
        0,
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::SyncObject, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::SyncObject, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::SyncObject, _impl_.public__),
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::SyncObject, _impl_.position_),
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::SyncObject, _impl_.rotation_),
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::SyncObject, _impl_.scale_),
        0,
        ~0u,
        ~0u,
        ~0u,
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::AddRemote, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::AddRemote, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::AddRemote, _impl_.grantnumber_),
        0,
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::AddObject, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::AddObject, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::AddObject, _impl_.grantnumber_),
        PROTOBUF_FIELD_OFFSET(::ConnectMsg::AddObject, _impl_.resourceid_),
        1,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::ConnectMsg::EnterAccept)},
        {10, 20, -1, sizeof(::ConnectMsg::SyncPlayer)},
        {22, 34, -1, sizeof(::ConnectMsg::SyncObject)},
        {38, 47, -1, sizeof(::ConnectMsg::AddRemote)},
        {48, 58, -1, sizeof(::ConnectMsg::AddObject)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::ConnectMsg::_EnterAccept_default_instance_._instance,
    &::ConnectMsg::_SyncPlayer_default_instance_._instance,
    &::ConnectMsg::_SyncObject_default_instance_._instance,
    &::ConnectMsg::_AddRemote_default_instance_._instance,
    &::ConnectMsg::_AddObject_default_instance_._instance,
};
const char descriptor_table_protodef_Connect_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rConnect.proto\022\nConnectMsg\"7\n\013EnterAcce"
    "pt\022\030\n\013grantnumber\030\001 \001(\005H\000\210\001\001B\016\n\014_grantnu"
    "mber\"B\n\nSyncPlayer\022\020\n\010position\030\001 \003(\002\022\025\n\010"
    "resource\030\002 \001(\tH\000\210\001\001B\013\n\t_resource\"_\n\nSync"
    "Object\022\023\n\006public\030\001 \001(\010H\000\210\001\001\022\020\n\010position\030"
    "\002 \003(\002\022\020\n\010rotation\030\003 \003(\002\022\r\n\005scale\030\004 \003(\002B\t"
    "\n\007_public\"5\n\tAddRemote\022\030\n\013grantnumber\030\001 "
    "\001(\005H\000\210\001\001B\016\n\014_grantnumber\"]\n\tAddObject\022\030\n"
    "\013grantnumber\030\001 \001(\005H\000\210\001\001\022\027\n\nresourceid\030\002 "
    "\001(\tH\001\210\001\001B\016\n\014_grantnumberB\r\n\013_resourceidb"
    "\006proto3"
};
static ::absl::once_flag descriptor_table_Connect_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Connect_2eproto = {
    false,
    false,
    407,
    descriptor_table_protodef_Connect_2eproto,
    "Connect.proto",
    &descriptor_table_Connect_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_Connect_2eproto::offsets,
    file_level_enum_descriptors_Connect_2eproto,
    file_level_service_descriptors_Connect_2eproto,
};
namespace ConnectMsg {
// ===================================================================

class EnterAccept::_Internal {
 public:
  using HasBits =
      decltype(std::declval<EnterAccept>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(EnterAccept, _impl_._has_bits_);
};

EnterAccept::EnterAccept(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ConnectMsg.EnterAccept)
}
EnterAccept::EnterAccept(
    ::google::protobuf::Arena* arena, const EnterAccept& from)
    : EnterAccept(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE EnterAccept::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void EnterAccept::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.grantnumber_ = {};
}
EnterAccept::~EnterAccept() {
  // @@protoc_insertion_point(destructor:ConnectMsg.EnterAccept)
  SharedDtor(*this);
}
inline void EnterAccept::SharedDtor(MessageLite& self) {
  EnterAccept& this_ = static_cast<EnterAccept&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* EnterAccept::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) EnterAccept(arena);
}
constexpr auto EnterAccept::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(EnterAccept),
                                            alignof(EnterAccept));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull EnterAccept::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_EnterAccept_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &EnterAccept::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<EnterAccept>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &EnterAccept::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<EnterAccept>(), &EnterAccept::ByteSizeLong,
            &EnterAccept::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(EnterAccept, _impl_._cached_size_),
        false,
    },
    &EnterAccept::kDescriptorMethods,
    &descriptor_table_Connect_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* EnterAccept::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> EnterAccept::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EnterAccept, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ConnectMsg::EnterAccept>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int32 grantnumber = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(EnterAccept, _impl_.grantnumber_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(EnterAccept, _impl_.grantnumber_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 grantnumber = 1;
    {PROTOBUF_FIELD_OFFSET(EnterAccept, _impl_.grantnumber_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void EnterAccept::Clear() {
// @@protoc_insertion_point(message_clear_start:ConnectMsg.EnterAccept)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.grantnumber_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* EnterAccept::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const EnterAccept& this_ = static_cast<const EnterAccept&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* EnterAccept::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const EnterAccept& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ConnectMsg.EnterAccept)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional int32 grantnumber = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_grantnumber(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ConnectMsg.EnterAccept)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t EnterAccept::ByteSizeLong(const MessageLite& base) {
          const EnterAccept& this_ = static_cast<const EnterAccept&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t EnterAccept::ByteSizeLong() const {
          const EnterAccept& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ConnectMsg.EnterAccept)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // optional int32 grantnumber = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_grantnumber());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void EnterAccept::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EnterAccept*>(&to_msg);
  auto& from = static_cast<const EnterAccept&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ConnectMsg.EnterAccept)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_impl_.grantnumber_ = from._impl_.grantnumber_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EnterAccept::CopyFrom(const EnterAccept& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ConnectMsg.EnterAccept)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EnterAccept::InternalSwap(EnterAccept* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
        swap(_impl_.grantnumber_, other->_impl_.grantnumber_);
}

::google::protobuf::Metadata EnterAccept::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SyncPlayer::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SyncPlayer>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SyncPlayer, _impl_._has_bits_);
};

SyncPlayer::SyncPlayer(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ConnectMsg.SyncPlayer)
}
inline PROTOBUF_NDEBUG_INLINE SyncPlayer::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ConnectMsg::SyncPlayer& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        position_{visibility, arena, from.position_},
        resource_(arena, from.resource_) {}

SyncPlayer::SyncPlayer(
    ::google::protobuf::Arena* arena,
    const SyncPlayer& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SyncPlayer* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:ConnectMsg.SyncPlayer)
}
inline PROTOBUF_NDEBUG_INLINE SyncPlayer::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        position_{visibility, arena},
        resource_(arena) {}

inline void SyncPlayer::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SyncPlayer::~SyncPlayer() {
  // @@protoc_insertion_point(destructor:ConnectMsg.SyncPlayer)
  SharedDtor(*this);
}
inline void SyncPlayer::SharedDtor(MessageLite& self) {
  SyncPlayer& this_ = static_cast<SyncPlayer&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.resource_.Destroy();
  this_._impl_.~Impl_();
}

inline void* SyncPlayer::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SyncPlayer(arena);
}
constexpr auto SyncPlayer::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SyncPlayer, _impl_.position_) +
          decltype(SyncPlayer::_impl_.position_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(SyncPlayer), alignof(SyncPlayer), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SyncPlayer::PlacementNew_,
                                 sizeof(SyncPlayer),
                                 alignof(SyncPlayer));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SyncPlayer::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SyncPlayer_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SyncPlayer::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SyncPlayer>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SyncPlayer::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SyncPlayer>(), &SyncPlayer::ByteSizeLong,
            &SyncPlayer::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SyncPlayer, _impl_._cached_size_),
        false,
    },
    &SyncPlayer::kDescriptorMethods,
    &descriptor_table_Connect_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SyncPlayer::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 38, 2> SyncPlayer::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SyncPlayer, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ConnectMsg::SyncPlayer>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional string resource = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(SyncPlayer, _impl_.resource_)}},
    // repeated float position = 1;
    {::_pbi::TcParser::FastF32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SyncPlayer, _impl_.position_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated float position = 1;
    {PROTOBUF_FIELD_OFFSET(SyncPlayer, _impl_.position_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // optional string resource = 2;
    {PROTOBUF_FIELD_OFFSET(SyncPlayer, _impl_.resource_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\25\0\10\0\0\0\0\0"
    "ConnectMsg.SyncPlayer"
    "resource"
  }},
};

PROTOBUF_NOINLINE void SyncPlayer::Clear() {
// @@protoc_insertion_point(message_clear_start:ConnectMsg.SyncPlayer)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.position_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.resource_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SyncPlayer::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SyncPlayer& this_ = static_cast<const SyncPlayer&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SyncPlayer::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SyncPlayer& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ConnectMsg.SyncPlayer)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated float position = 1;
          if (this_._internal_position_size() > 0) {
            target = stream->WriteFixedPacked(1, this_._internal_position(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional string resource = 2;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_resource();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ConnectMsg.SyncPlayer.resource");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ConnectMsg.SyncPlayer)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SyncPlayer::ByteSizeLong(const MessageLite& base) {
          const SyncPlayer& this_ = static_cast<const SyncPlayer&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SyncPlayer::ByteSizeLong() const {
          const SyncPlayer& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ConnectMsg.SyncPlayer)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated float position = 1;
            {
              std::size_t data_size = std::size_t{4} *
                  ::_pbi::FromIntSize(this_._internal_position_size());
              std::size_t tag_size = data_size == 0
                  ? 0
                  : 1 + ::_pbi::WireFormatLite::Int32Size(
                                      static_cast<int32_t>(data_size));
              total_size += tag_size + data_size;
            }
          }
           {
            // optional string resource = 2;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_resource());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SyncPlayer::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SyncPlayer*>(&to_msg);
  auto& from = static_cast<const SyncPlayer&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ConnectMsg.SyncPlayer)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_position()->MergeFrom(from._internal_position());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_internal_set_resource(from._internal_resource());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SyncPlayer::CopyFrom(const SyncPlayer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ConnectMsg.SyncPlayer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SyncPlayer::InternalSwap(SyncPlayer* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.position_.InternalSwap(&other->_impl_.position_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.resource_, &other->_impl_.resource_, arena);
}

::google::protobuf::Metadata SyncPlayer::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SyncObject::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SyncObject>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SyncObject, _impl_._has_bits_);
};

SyncObject::SyncObject(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ConnectMsg.SyncObject)
}
inline PROTOBUF_NDEBUG_INLINE SyncObject::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ConnectMsg::SyncObject& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        position_{visibility, arena, from.position_},
        rotation_{visibility, arena, from.rotation_},
        scale_{visibility, arena, from.scale_} {}

SyncObject::SyncObject(
    ::google::protobuf::Arena* arena,
    const SyncObject& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SyncObject* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.public__ = from._impl_.public__;

  // @@protoc_insertion_point(copy_constructor:ConnectMsg.SyncObject)
}
inline PROTOBUF_NDEBUG_INLINE SyncObject::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        position_{visibility, arena},
        rotation_{visibility, arena},
        scale_{visibility, arena} {}

inline void SyncObject::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.public__ = {};
}
SyncObject::~SyncObject() {
  // @@protoc_insertion_point(destructor:ConnectMsg.SyncObject)
  SharedDtor(*this);
}
inline void SyncObject::SharedDtor(MessageLite& self) {
  SyncObject& this_ = static_cast<SyncObject&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* SyncObject::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SyncObject(arena);
}
constexpr auto SyncObject::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SyncObject, _impl_.position_) +
          decltype(SyncObject::_impl_.position_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(SyncObject, _impl_.rotation_) +
          decltype(SyncObject::_impl_.rotation_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(SyncObject, _impl_.scale_) +
          decltype(SyncObject::_impl_.scale_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(SyncObject), alignof(SyncObject), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SyncObject::PlacementNew_,
                                 sizeof(SyncObject),
                                 alignof(SyncObject));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SyncObject::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SyncObject_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SyncObject::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SyncObject>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SyncObject::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SyncObject>(), &SyncObject::ByteSizeLong,
            &SyncObject::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SyncObject, _impl_._cached_size_),
        false,
    },
    &SyncObject::kDescriptorMethods,
    &descriptor_table_Connect_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SyncObject::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> SyncObject::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SyncObject, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ConnectMsg::SyncObject>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated float scale = 4;
    {::_pbi::TcParser::FastF32P1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(SyncObject, _impl_.scale_)}},
    // optional bool public = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SyncObject, _impl_.public__), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(SyncObject, _impl_.public__)}},
    // repeated float position = 2;
    {::_pbi::TcParser::FastF32P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(SyncObject, _impl_.position_)}},
    // repeated float rotation = 3;
    {::_pbi::TcParser::FastF32P1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(SyncObject, _impl_.rotation_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional bool public = 1;
    {PROTOBUF_FIELD_OFFSET(SyncObject, _impl_.public__), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // repeated float position = 2;
    {PROTOBUF_FIELD_OFFSET(SyncObject, _impl_.position_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float rotation = 3;
    {PROTOBUF_FIELD_OFFSET(SyncObject, _impl_.rotation_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float scale = 4;
    {PROTOBUF_FIELD_OFFSET(SyncObject, _impl_.scale_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void SyncObject::Clear() {
// @@protoc_insertion_point(message_clear_start:ConnectMsg.SyncObject)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.position_.Clear();
  _impl_.rotation_.Clear();
  _impl_.scale_.Clear();
  _impl_.public__ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SyncObject::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SyncObject& this_ = static_cast<const SyncObject&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SyncObject::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SyncObject& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ConnectMsg.SyncObject)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional bool public = 1;
          if (cached_has_bits & 0x00000001u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_public_(), target);
          }

          // repeated float position = 2;
          if (this_._internal_position_size() > 0) {
            target = stream->WriteFixedPacked(2, this_._internal_position(), target);
          }

          // repeated float rotation = 3;
          if (this_._internal_rotation_size() > 0) {
            target = stream->WriteFixedPacked(3, this_._internal_rotation(), target);
          }

          // repeated float scale = 4;
          if (this_._internal_scale_size() > 0) {
            target = stream->WriteFixedPacked(4, this_._internal_scale(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ConnectMsg.SyncObject)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SyncObject::ByteSizeLong(const MessageLite& base) {
          const SyncObject& this_ = static_cast<const SyncObject&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SyncObject::ByteSizeLong() const {
          const SyncObject& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ConnectMsg.SyncObject)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated float position = 2;
            {
              std::size_t data_size = std::size_t{4} *
                  ::_pbi::FromIntSize(this_._internal_position_size());
              std::size_t tag_size = data_size == 0
                  ? 0
                  : 1 + ::_pbi::WireFormatLite::Int32Size(
                                      static_cast<int32_t>(data_size));
              total_size += tag_size + data_size;
            }
            // repeated float rotation = 3;
            {
              std::size_t data_size = std::size_t{4} *
                  ::_pbi::FromIntSize(this_._internal_rotation_size());
              std::size_t tag_size = data_size == 0
                  ? 0
                  : 1 + ::_pbi::WireFormatLite::Int32Size(
                                      static_cast<int32_t>(data_size));
              total_size += tag_size + data_size;
            }
            // repeated float scale = 4;
            {
              std::size_t data_size = std::size_t{4} *
                  ::_pbi::FromIntSize(this_._internal_scale_size());
              std::size_t tag_size = data_size == 0
                  ? 0
                  : 1 + ::_pbi::WireFormatLite::Int32Size(
                                      static_cast<int32_t>(data_size));
              total_size += tag_size + data_size;
            }
          }
           {
            // optional bool public = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SyncObject::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SyncObject*>(&to_msg);
  auto& from = static_cast<const SyncObject&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ConnectMsg.SyncObject)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_position()->MergeFrom(from._internal_position());
  _this->_internal_mutable_rotation()->MergeFrom(from._internal_rotation());
  _this->_internal_mutable_scale()->MergeFrom(from._internal_scale());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_impl_.public__ = from._impl_.public__;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SyncObject::CopyFrom(const SyncObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ConnectMsg.SyncObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SyncObject::InternalSwap(SyncObject* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.position_.InternalSwap(&other->_impl_.position_);
  _impl_.rotation_.InternalSwap(&other->_impl_.rotation_);
  _impl_.scale_.InternalSwap(&other->_impl_.scale_);
        swap(_impl_.public__, other->_impl_.public__);
}

::google::protobuf::Metadata SyncObject::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AddRemote::_Internal {
 public:
  using HasBits =
      decltype(std::declval<AddRemote>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AddRemote, _impl_._has_bits_);
};

AddRemote::AddRemote(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ConnectMsg.AddRemote)
}
AddRemote::AddRemote(
    ::google::protobuf::Arena* arena, const AddRemote& from)
    : AddRemote(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE AddRemote::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void AddRemote::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.grantnumber_ = {};
}
AddRemote::~AddRemote() {
  // @@protoc_insertion_point(destructor:ConnectMsg.AddRemote)
  SharedDtor(*this);
}
inline void AddRemote::SharedDtor(MessageLite& self) {
  AddRemote& this_ = static_cast<AddRemote&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* AddRemote::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) AddRemote(arena);
}
constexpr auto AddRemote::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(AddRemote),
                                            alignof(AddRemote));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull AddRemote::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_AddRemote_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &AddRemote::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<AddRemote>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &AddRemote::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<AddRemote>(), &AddRemote::ByteSizeLong,
            &AddRemote::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(AddRemote, _impl_._cached_size_),
        false,
    },
    &AddRemote::kDescriptorMethods,
    &descriptor_table_Connect_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* AddRemote::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> AddRemote::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AddRemote, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ConnectMsg::AddRemote>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int32 grantnumber = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AddRemote, _impl_.grantnumber_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(AddRemote, _impl_.grantnumber_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 grantnumber = 1;
    {PROTOBUF_FIELD_OFFSET(AddRemote, _impl_.grantnumber_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void AddRemote::Clear() {
// @@protoc_insertion_point(message_clear_start:ConnectMsg.AddRemote)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.grantnumber_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* AddRemote::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const AddRemote& this_ = static_cast<const AddRemote&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* AddRemote::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const AddRemote& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ConnectMsg.AddRemote)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional int32 grantnumber = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_grantnumber(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ConnectMsg.AddRemote)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t AddRemote::ByteSizeLong(const MessageLite& base) {
          const AddRemote& this_ = static_cast<const AddRemote&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t AddRemote::ByteSizeLong() const {
          const AddRemote& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ConnectMsg.AddRemote)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // optional int32 grantnumber = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_grantnumber());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void AddRemote::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AddRemote*>(&to_msg);
  auto& from = static_cast<const AddRemote&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ConnectMsg.AddRemote)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_impl_.grantnumber_ = from._impl_.grantnumber_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AddRemote::CopyFrom(const AddRemote& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ConnectMsg.AddRemote)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AddRemote::InternalSwap(AddRemote* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
        swap(_impl_.grantnumber_, other->_impl_.grantnumber_);
}

::google::protobuf::Metadata AddRemote::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AddObject::_Internal {
 public:
  using HasBits =
      decltype(std::declval<AddObject>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AddObject, _impl_._has_bits_);
};

AddObject::AddObject(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ConnectMsg.AddObject)
}
inline PROTOBUF_NDEBUG_INLINE AddObject::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ConnectMsg::AddObject& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        resourceid_(arena, from.resourceid_) {}

AddObject::AddObject(
    ::google::protobuf::Arena* arena,
    const AddObject& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AddObject* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.grantnumber_ = from._impl_.grantnumber_;

  // @@protoc_insertion_point(copy_constructor:ConnectMsg.AddObject)
}
inline PROTOBUF_NDEBUG_INLINE AddObject::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        resourceid_(arena) {}

inline void AddObject::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.grantnumber_ = {};
}
AddObject::~AddObject() {
  // @@protoc_insertion_point(destructor:ConnectMsg.AddObject)
  SharedDtor(*this);
}
inline void AddObject::SharedDtor(MessageLite& self) {
  AddObject& this_ = static_cast<AddObject&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.resourceid_.Destroy();
  this_._impl_.~Impl_();
}

inline void* AddObject::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) AddObject(arena);
}
constexpr auto AddObject::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AddObject),
                                            alignof(AddObject));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull AddObject::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_AddObject_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &AddObject::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<AddObject>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &AddObject::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<AddObject>(), &AddObject::ByteSizeLong,
            &AddObject::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(AddObject, _impl_._cached_size_),
        false,
    },
    &AddObject::kDescriptorMethods,
    &descriptor_table_Connect_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* AddObject::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 39, 2> AddObject::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AddObject, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ConnectMsg::AddObject>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional string resourceid = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(AddObject, _impl_.resourceid_)}},
    // optional int32 grantnumber = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AddObject, _impl_.grantnumber_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(AddObject, _impl_.grantnumber_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 grantnumber = 1;
    {PROTOBUF_FIELD_OFFSET(AddObject, _impl_.grantnumber_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string resourceid = 2;
    {PROTOBUF_FIELD_OFFSET(AddObject, _impl_.resourceid_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\0\12\0\0\0\0\0"
    "ConnectMsg.AddObject"
    "resourceid"
  }},
};

PROTOBUF_NOINLINE void AddObject::Clear() {
// @@protoc_insertion_point(message_clear_start:ConnectMsg.AddObject)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.resourceid_.ClearNonDefaultToEmpty();
  }
  _impl_.grantnumber_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* AddObject::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const AddObject& this_ = static_cast<const AddObject&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* AddObject::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const AddObject& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ConnectMsg.AddObject)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional int32 grantnumber = 1;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_grantnumber(), target);
          }

          // optional string resourceid = 2;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_resourceid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ConnectMsg.AddObject.resourceid");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ConnectMsg.AddObject)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t AddObject::ByteSizeLong(const MessageLite& base) {
          const AddObject& this_ = static_cast<const AddObject&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t AddObject::ByteSizeLong() const {
          const AddObject& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ConnectMsg.AddObject)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // optional string resourceid = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_resourceid());
            }
            // optional int32 grantnumber = 1;
            if (cached_has_bits & 0x00000002u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_grantnumber());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void AddObject::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AddObject*>(&to_msg);
  auto& from = static_cast<const AddObject&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ConnectMsg.AddObject)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_resourceid(from._internal_resourceid());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.grantnumber_ = from._impl_.grantnumber_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AddObject::CopyFrom(const AddObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ConnectMsg.AddObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AddObject::InternalSwap(AddObject* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.resourceid_, &other->_impl_.resourceid_, arena);
        swap(_impl_.grantnumber_, other->_impl_.grantnumber_);
}

::google::protobuf::Metadata AddObject::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace ConnectMsg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Connect_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
