// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Connect.proto
// Protobuf C++ Version: 5.29.2

#ifndef Connect_2eproto_2epb_2eh
#define Connect_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Connect_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Connect_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Connect_2eproto;
namespace ConnectMsg {
class AddObject;
struct AddObjectDefaultTypeInternal;
extern AddObjectDefaultTypeInternal _AddObject_default_instance_;
class AddRemote;
struct AddRemoteDefaultTypeInternal;
extern AddRemoteDefaultTypeInternal _AddRemote_default_instance_;
class EnterAccept;
struct EnterAcceptDefaultTypeInternal;
extern EnterAcceptDefaultTypeInternal _EnterAccept_default_instance_;
class SyncObject;
struct SyncObjectDefaultTypeInternal;
extern SyncObjectDefaultTypeInternal _SyncObject_default_instance_;
class SyncPlayer;
struct SyncPlayerDefaultTypeInternal;
extern SyncPlayerDefaultTypeInternal _SyncPlayer_default_instance_;
}  // namespace ConnectMsg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace ConnectMsg {

// ===================================================================


// -------------------------------------------------------------------

class SyncPlayer final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ConnectMsg.SyncPlayer) */ {
 public:
  inline SyncPlayer() : SyncPlayer(nullptr) {}
  ~SyncPlayer() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SyncPlayer* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SyncPlayer));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SyncPlayer(
      ::google::protobuf::internal::ConstantInitialized);

  inline SyncPlayer(const SyncPlayer& from) : SyncPlayer(nullptr, from) {}
  inline SyncPlayer(SyncPlayer&& from) noexcept
      : SyncPlayer(nullptr, std::move(from)) {}
  inline SyncPlayer& operator=(const SyncPlayer& from) {
    CopyFrom(from);
    return *this;
  }
  inline SyncPlayer& operator=(SyncPlayer&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SyncPlayer& default_instance() {
    return *internal_default_instance();
  }
  static inline const SyncPlayer* internal_default_instance() {
    return reinterpret_cast<const SyncPlayer*>(
        &_SyncPlayer_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SyncPlayer& a, SyncPlayer& b) { a.Swap(&b); }
  inline void Swap(SyncPlayer* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SyncPlayer* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SyncPlayer* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SyncPlayer>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SyncPlayer& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SyncPlayer& from) { SyncPlayer::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SyncPlayer* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ConnectMsg.SyncPlayer"; }

 protected:
  explicit SyncPlayer(::google::protobuf::Arena* arena);
  SyncPlayer(::google::protobuf::Arena* arena, const SyncPlayer& from);
  SyncPlayer(::google::protobuf::Arena* arena, SyncPlayer&& from) noexcept
      : SyncPlayer(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResourceFieldNumber = 4,
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // optional string resource = 4;
  bool has_resource() const;
  void clear_resource() ;
  const std::string& resource() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_resource(Arg_&& arg, Args_... args);
  std::string* mutable_resource();
  PROTOBUF_NODISCARD std::string* release_resource();
  void set_allocated_resource(std::string* value);

  private:
  const std::string& _internal_resource() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_resource(
      const std::string& value);
  std::string* _internal_mutable_resource();

  public:
  // optional float x = 1;
  bool has_x() const;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // optional float y = 2;
  bool has_y() const;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // optional float z = 3;
  bool has_z() const;
  void clear_z() ;
  float z() const;
  void set_z(float value);

  private:
  float _internal_z() const;
  void _internal_set_z(float value);

  public:
  // @@protoc_insertion_point(class_scope:ConnectMsg.SyncPlayer)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      38, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SyncPlayer& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr resource_;
    float x_;
    float y_;
    float z_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Connect_2eproto;
};
// -------------------------------------------------------------------

class SyncObject final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ConnectMsg.SyncObject) */ {
 public:
  inline SyncObject() : SyncObject(nullptr) {}
  ~SyncObject() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SyncObject* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SyncObject));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SyncObject(
      ::google::protobuf::internal::ConstantInitialized);

  inline SyncObject(const SyncObject& from) : SyncObject(nullptr, from) {}
  inline SyncObject(SyncObject&& from) noexcept
      : SyncObject(nullptr, std::move(from)) {}
  inline SyncObject& operator=(const SyncObject& from) {
    CopyFrom(from);
    return *this;
  }
  inline SyncObject& operator=(SyncObject&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SyncObject& default_instance() {
    return *internal_default_instance();
  }
  static inline const SyncObject* internal_default_instance() {
    return reinterpret_cast<const SyncObject*>(
        &_SyncObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(SyncObject& a, SyncObject& b) { a.Swap(&b); }
  inline void Swap(SyncObject* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SyncObject* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SyncObject* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SyncObject>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SyncObject& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SyncObject& from) { SyncObject::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SyncObject* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ConnectMsg.SyncObject"; }

 protected:
  explicit SyncObject(::google::protobuf::Arena* arena);
  SyncObject(::google::protobuf::Arena* arena, const SyncObject& from);
  SyncObject(::google::protobuf::Arena* arena, SyncObject&& from) noexcept
      : SyncObject(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPositionFieldNumber = 2,
    kRotationFieldNumber = 3,
    kScaleFieldNumber = 4,
    kPublicFieldNumber = 1,
  };
  // repeated float position = 2;
  int position_size() const;
  private:
  int _internal_position_size() const;

  public:
  void clear_position() ;
  float position(int index) const;
  void set_position(int index, float value);
  void add_position(float value);
  const ::google::protobuf::RepeatedField<float>& position() const;
  ::google::protobuf::RepeatedField<float>* mutable_position();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_position() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_position();

  public:
  // repeated float rotation = 3;
  int rotation_size() const;
  private:
  int _internal_rotation_size() const;

  public:
  void clear_rotation() ;
  float rotation(int index) const;
  void set_rotation(int index, float value);
  void add_rotation(float value);
  const ::google::protobuf::RepeatedField<float>& rotation() const;
  ::google::protobuf::RepeatedField<float>* mutable_rotation();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_rotation() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_rotation();

  public:
  // repeated float scale = 4;
  int scale_size() const;
  private:
  int _internal_scale_size() const;

  public:
  void clear_scale() ;
  float scale(int index) const;
  void set_scale(int index, float value);
  void add_scale(float value);
  const ::google::protobuf::RepeatedField<float>& scale() const;
  ::google::protobuf::RepeatedField<float>* mutable_scale();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_scale() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_scale();

  public:
  // optional bool public = 1;
  bool has_public_() const;
  void clear_public_() ;
  bool public_() const;
  void set_public_(bool value);

  private:
  bool _internal_public_() const;
  void _internal_set_public_(bool value);

  public:
  // @@protoc_insertion_point(class_scope:ConnectMsg.SyncObject)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SyncObject& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<float> position_;
    ::google::protobuf::RepeatedField<float> rotation_;
    ::google::protobuf::RepeatedField<float> scale_;
    bool public__;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Connect_2eproto;
};
// -------------------------------------------------------------------

class EnterAccept final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ConnectMsg.EnterAccept) */ {
 public:
  inline EnterAccept() : EnterAccept(nullptr) {}
  ~EnterAccept() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EnterAccept* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EnterAccept));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EnterAccept(
      ::google::protobuf::internal::ConstantInitialized);

  inline EnterAccept(const EnterAccept& from) : EnterAccept(nullptr, from) {}
  inline EnterAccept(EnterAccept&& from) noexcept
      : EnterAccept(nullptr, std::move(from)) {}
  inline EnterAccept& operator=(const EnterAccept& from) {
    CopyFrom(from);
    return *this;
  }
  inline EnterAccept& operator=(EnterAccept&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EnterAccept& default_instance() {
    return *internal_default_instance();
  }
  static inline const EnterAccept* internal_default_instance() {
    return reinterpret_cast<const EnterAccept*>(
        &_EnterAccept_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(EnterAccept& a, EnterAccept& b) { a.Swap(&b); }
  inline void Swap(EnterAccept* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EnterAccept* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EnterAccept* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EnterAccept>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EnterAccept& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EnterAccept& from) { EnterAccept::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EnterAccept* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ConnectMsg.EnterAccept"; }

 protected:
  explicit EnterAccept(::google::protobuf::Arena* arena);
  EnterAccept(::google::protobuf::Arena* arena, const EnterAccept& from);
  EnterAccept(::google::protobuf::Arena* arena, EnterAccept&& from) noexcept
      : EnterAccept(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kGrantnumberFieldNumber = 1,
  };
  // optional int32 grantnumber = 1;
  bool has_grantnumber() const;
  void clear_grantnumber() ;
  ::int32_t grantnumber() const;
  void set_grantnumber(::int32_t value);

  private:
  ::int32_t _internal_grantnumber() const;
  void _internal_set_grantnumber(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:ConnectMsg.EnterAccept)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const EnterAccept& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t grantnumber_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Connect_2eproto;
};
// -------------------------------------------------------------------

class AddRemote final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ConnectMsg.AddRemote) */ {
 public:
  inline AddRemote() : AddRemote(nullptr) {}
  ~AddRemote() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AddRemote* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AddRemote));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AddRemote(
      ::google::protobuf::internal::ConstantInitialized);

  inline AddRemote(const AddRemote& from) : AddRemote(nullptr, from) {}
  inline AddRemote(AddRemote&& from) noexcept
      : AddRemote(nullptr, std::move(from)) {}
  inline AddRemote& operator=(const AddRemote& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddRemote& operator=(AddRemote&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddRemote& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddRemote* internal_default_instance() {
    return reinterpret_cast<const AddRemote*>(
        &_AddRemote_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(AddRemote& a, AddRemote& b) { a.Swap(&b); }
  inline void Swap(AddRemote* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddRemote* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddRemote* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AddRemote>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AddRemote& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AddRemote& from) { AddRemote::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AddRemote* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ConnectMsg.AddRemote"; }

 protected:
  explicit AddRemote(::google::protobuf::Arena* arena);
  AddRemote(::google::protobuf::Arena* arena, const AddRemote& from);
  AddRemote(::google::protobuf::Arena* arena, AddRemote&& from) noexcept
      : AddRemote(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kGrantnumberFieldNumber = 1,
  };
  // optional int32 grantnumber = 1;
  bool has_grantnumber() const;
  void clear_grantnumber() ;
  ::int32_t grantnumber() const;
  void set_grantnumber(::int32_t value);

  private:
  ::int32_t _internal_grantnumber() const;
  void _internal_set_grantnumber(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:ConnectMsg.AddRemote)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AddRemote& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t grantnumber_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Connect_2eproto;
};
// -------------------------------------------------------------------

class AddObject final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ConnectMsg.AddObject) */ {
 public:
  inline AddObject() : AddObject(nullptr) {}
  ~AddObject() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AddObject* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AddObject));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AddObject(
      ::google::protobuf::internal::ConstantInitialized);

  inline AddObject(const AddObject& from) : AddObject(nullptr, from) {}
  inline AddObject(AddObject&& from) noexcept
      : AddObject(nullptr, std::move(from)) {}
  inline AddObject& operator=(const AddObject& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddObject& operator=(AddObject&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddObject& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddObject* internal_default_instance() {
    return reinterpret_cast<const AddObject*>(
        &_AddObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(AddObject& a, AddObject& b) { a.Swap(&b); }
  inline void Swap(AddObject* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddObject* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddObject* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AddObject>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AddObject& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AddObject& from) { AddObject::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AddObject* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ConnectMsg.AddObject"; }

 protected:
  explicit AddObject(::google::protobuf::Arena* arena);
  AddObject(::google::protobuf::Arena* arena, const AddObject& from);
  AddObject(::google::protobuf::Arena* arena, AddObject&& from) noexcept
      : AddObject(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResourceidFieldNumber = 2,
    kGrantnumberFieldNumber = 1,
  };
  // optional string resourceid = 2;
  bool has_resourceid() const;
  void clear_resourceid() ;
  const std::string& resourceid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_resourceid(Arg_&& arg, Args_... args);
  std::string* mutable_resourceid();
  PROTOBUF_NODISCARD std::string* release_resourceid();
  void set_allocated_resourceid(std::string* value);

  private:
  const std::string& _internal_resourceid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_resourceid(
      const std::string& value);
  std::string* _internal_mutable_resourceid();

  public:
  // optional int32 grantnumber = 1;
  bool has_grantnumber() const;
  void clear_grantnumber() ;
  ::int32_t grantnumber() const;
  void set_grantnumber(::int32_t value);

  private:
  ::int32_t _internal_grantnumber() const;
  void _internal_set_grantnumber(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:ConnectMsg.AddObject)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      39, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AddObject& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr resourceid_;
    ::int32_t grantnumber_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Connect_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// EnterAccept

// optional int32 grantnumber = 1;
inline bool EnterAccept::has_grantnumber() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void EnterAccept::clear_grantnumber() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.grantnumber_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t EnterAccept::grantnumber() const {
  // @@protoc_insertion_point(field_get:ConnectMsg.EnterAccept.grantnumber)
  return _internal_grantnumber();
}
inline void EnterAccept::set_grantnumber(::int32_t value) {
  _internal_set_grantnumber(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:ConnectMsg.EnterAccept.grantnumber)
}
inline ::int32_t EnterAccept::_internal_grantnumber() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.grantnumber_;
}
inline void EnterAccept::_internal_set_grantnumber(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.grantnumber_ = value;
}

// -------------------------------------------------------------------

// SyncPlayer

// optional float x = 1;
inline bool SyncPlayer::has_x() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void SyncPlayer::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline float SyncPlayer::x() const {
  // @@protoc_insertion_point(field_get:ConnectMsg.SyncPlayer.x)
  return _internal_x();
}
inline void SyncPlayer::set_x(float value) {
  _internal_set_x(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:ConnectMsg.SyncPlayer.x)
}
inline float SyncPlayer::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void SyncPlayer::_internal_set_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// optional float y = 2;
inline bool SyncPlayer::has_y() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void SyncPlayer::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline float SyncPlayer::y() const {
  // @@protoc_insertion_point(field_get:ConnectMsg.SyncPlayer.y)
  return _internal_y();
}
inline void SyncPlayer::set_y(float value) {
  _internal_set_y(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:ConnectMsg.SyncPlayer.y)
}
inline float SyncPlayer::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void SyncPlayer::_internal_set_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// optional float z = 3;
inline bool SyncPlayer::has_z() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void SyncPlayer::clear_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline float SyncPlayer::z() const {
  // @@protoc_insertion_point(field_get:ConnectMsg.SyncPlayer.z)
  return _internal_z();
}
inline void SyncPlayer::set_z(float value) {
  _internal_set_z(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:ConnectMsg.SyncPlayer.z)
}
inline float SyncPlayer::_internal_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.z_;
}
inline void SyncPlayer::_internal_set_z(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = value;
}

// optional string resource = 4;
inline bool SyncPlayer::has_resource() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void SyncPlayer::clear_resource() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resource_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SyncPlayer::resource() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ConnectMsg.SyncPlayer.resource)
  return _internal_resource();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SyncPlayer::set_resource(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.resource_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ConnectMsg.SyncPlayer.resource)
}
inline std::string* SyncPlayer::mutable_resource() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_resource();
  // @@protoc_insertion_point(field_mutable:ConnectMsg.SyncPlayer.resource)
  return _s;
}
inline const std::string& SyncPlayer::_internal_resource() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.resource_.Get();
}
inline void SyncPlayer::_internal_set_resource(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.resource_.Set(value, GetArena());
}
inline std::string* SyncPlayer::_internal_mutable_resource() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.resource_.Mutable( GetArena());
}
inline std::string* SyncPlayer::release_resource() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ConnectMsg.SyncPlayer.resource)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.resource_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.resource_.Set("", GetArena());
  }
  return released;
}
inline void SyncPlayer::set_allocated_resource(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.resource_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.resource_.IsDefault()) {
    _impl_.resource_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ConnectMsg.SyncPlayer.resource)
}

// -------------------------------------------------------------------

// SyncObject

// optional bool public = 1;
inline bool SyncObject::has_public_() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void SyncObject::clear_public_() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.public__ = false;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline bool SyncObject::public_() const {
  // @@protoc_insertion_point(field_get:ConnectMsg.SyncObject.public)
  return _internal_public_();
}
inline void SyncObject::set_public_(bool value) {
  _internal_set_public_(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:ConnectMsg.SyncObject.public)
}
inline bool SyncObject::_internal_public_() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.public__;
}
inline void SyncObject::_internal_set_public_(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.public__ = value;
}

// repeated float position = 2;
inline int SyncObject::_internal_position_size() const {
  return _internal_position().size();
}
inline int SyncObject::position_size() const {
  return _internal_position_size();
}
inline void SyncObject::clear_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_.Clear();
}
inline float SyncObject::position(int index) const {
  // @@protoc_insertion_point(field_get:ConnectMsg.SyncObject.position)
  return _internal_position().Get(index);
}
inline void SyncObject::set_position(int index, float value) {
  _internal_mutable_position()->Set(index, value);
  // @@protoc_insertion_point(field_set:ConnectMsg.SyncObject.position)
}
inline void SyncObject::add_position(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_position()->Add(value);
  // @@protoc_insertion_point(field_add:ConnectMsg.SyncObject.position)
}
inline const ::google::protobuf::RepeatedField<float>& SyncObject::position() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ConnectMsg.SyncObject.position)
  return _internal_position();
}
inline ::google::protobuf::RepeatedField<float>* SyncObject::mutable_position()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ConnectMsg.SyncObject.position)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_position();
}
inline const ::google::protobuf::RepeatedField<float>&
SyncObject::_internal_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.position_;
}
inline ::google::protobuf::RepeatedField<float>* SyncObject::_internal_mutable_position() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.position_;
}

// repeated float rotation = 3;
inline int SyncObject::_internal_rotation_size() const {
  return _internal_rotation().size();
}
inline int SyncObject::rotation_size() const {
  return _internal_rotation_size();
}
inline void SyncObject::clear_rotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rotation_.Clear();
}
inline float SyncObject::rotation(int index) const {
  // @@protoc_insertion_point(field_get:ConnectMsg.SyncObject.rotation)
  return _internal_rotation().Get(index);
}
inline void SyncObject::set_rotation(int index, float value) {
  _internal_mutable_rotation()->Set(index, value);
  // @@protoc_insertion_point(field_set:ConnectMsg.SyncObject.rotation)
}
inline void SyncObject::add_rotation(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_rotation()->Add(value);
  // @@protoc_insertion_point(field_add:ConnectMsg.SyncObject.rotation)
}
inline const ::google::protobuf::RepeatedField<float>& SyncObject::rotation() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ConnectMsg.SyncObject.rotation)
  return _internal_rotation();
}
inline ::google::protobuf::RepeatedField<float>* SyncObject::mutable_rotation()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ConnectMsg.SyncObject.rotation)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_rotation();
}
inline const ::google::protobuf::RepeatedField<float>&
SyncObject::_internal_rotation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rotation_;
}
inline ::google::protobuf::RepeatedField<float>* SyncObject::_internal_mutable_rotation() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.rotation_;
}

// repeated float scale = 4;
inline int SyncObject::_internal_scale_size() const {
  return _internal_scale().size();
}
inline int SyncObject::scale_size() const {
  return _internal_scale_size();
}
inline void SyncObject::clear_scale() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scale_.Clear();
}
inline float SyncObject::scale(int index) const {
  // @@protoc_insertion_point(field_get:ConnectMsg.SyncObject.scale)
  return _internal_scale().Get(index);
}
inline void SyncObject::set_scale(int index, float value) {
  _internal_mutable_scale()->Set(index, value);
  // @@protoc_insertion_point(field_set:ConnectMsg.SyncObject.scale)
}
inline void SyncObject::add_scale(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_scale()->Add(value);
  // @@protoc_insertion_point(field_add:ConnectMsg.SyncObject.scale)
}
inline const ::google::protobuf::RepeatedField<float>& SyncObject::scale() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ConnectMsg.SyncObject.scale)
  return _internal_scale();
}
inline ::google::protobuf::RepeatedField<float>* SyncObject::mutable_scale()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ConnectMsg.SyncObject.scale)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_scale();
}
inline const ::google::protobuf::RepeatedField<float>&
SyncObject::_internal_scale() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.scale_;
}
inline ::google::protobuf::RepeatedField<float>* SyncObject::_internal_mutable_scale() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.scale_;
}

// -------------------------------------------------------------------

// AddRemote

// optional int32 grantnumber = 1;
inline bool AddRemote::has_grantnumber() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void AddRemote::clear_grantnumber() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.grantnumber_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t AddRemote::grantnumber() const {
  // @@protoc_insertion_point(field_get:ConnectMsg.AddRemote.grantnumber)
  return _internal_grantnumber();
}
inline void AddRemote::set_grantnumber(::int32_t value) {
  _internal_set_grantnumber(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:ConnectMsg.AddRemote.grantnumber)
}
inline ::int32_t AddRemote::_internal_grantnumber() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.grantnumber_;
}
inline void AddRemote::_internal_set_grantnumber(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.grantnumber_ = value;
}

// -------------------------------------------------------------------

// AddObject

// optional int32 grantnumber = 1;
inline bool AddObject::has_grantnumber() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void AddObject::clear_grantnumber() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.grantnumber_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t AddObject::grantnumber() const {
  // @@protoc_insertion_point(field_get:ConnectMsg.AddObject.grantnumber)
  return _internal_grantnumber();
}
inline void AddObject::set_grantnumber(::int32_t value) {
  _internal_set_grantnumber(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:ConnectMsg.AddObject.grantnumber)
}
inline ::int32_t AddObject::_internal_grantnumber() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.grantnumber_;
}
inline void AddObject::_internal_set_grantnumber(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.grantnumber_ = value;
}

// optional string resourceid = 2;
inline bool AddObject::has_resourceid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void AddObject::clear_resourceid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resourceid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& AddObject::resourceid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ConnectMsg.AddObject.resourceid)
  return _internal_resourceid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AddObject::set_resourceid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.resourceid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ConnectMsg.AddObject.resourceid)
}
inline std::string* AddObject::mutable_resourceid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_resourceid();
  // @@protoc_insertion_point(field_mutable:ConnectMsg.AddObject.resourceid)
  return _s;
}
inline const std::string& AddObject::_internal_resourceid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.resourceid_.Get();
}
inline void AddObject::_internal_set_resourceid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.resourceid_.Set(value, GetArena());
}
inline std::string* AddObject::_internal_mutable_resourceid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.resourceid_.Mutable( GetArena());
}
inline std::string* AddObject::release_resourceid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ConnectMsg.AddObject.resourceid)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.resourceid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.resourceid_.Set("", GetArena());
  }
  return released;
}
inline void AddObject::set_allocated_resourceid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.resourceid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.resourceid_.IsDefault()) {
    _impl_.resourceid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ConnectMsg.AddObject.resourceid)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace ConnectMsg


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Connect_2eproto_2epb_2eh
