#pragma once

#include "IGraphicsSystem.h"
#include "ICameraSystem.h"
#include "IRenderSystem.h"
#include "IAnimationSystem.h"
#include "ILightSystem.h"
#include "ITextSystem.h"
#include "IPostProcessSystem.h"
#include "ISpriteSystem.h"
#include "IUnlitSystem.h"

#include "ICamera.h"
#include "IAnimator.h"
#include "Matrix4x4.h"
#include "ILight.h"
#include "IMeshRenderer.h"
#include "ITextRenderer.h"
#include "ISkyBoxRenderer.h"
#include "ISpriteRenderer.h"
#include "IUnlitRenderer.h"
#include "ILineRenderer.h"

#include "IBloom.h"
#include "IBlur.h"